runtime: php55
api_version: 1

handlers:

- url: /static
  static_dir: static

- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico
  
- url: /whitworth
  static_files: static/Myval268.htm
  upload: static/Myval268.htm
  mime_type: text/html; charset=UTF-8   
  
- url: /(.*)
  static_files: index.htm
  upload: index.htm
  mime_type: text/html; charset=UTF-8
    
- url: /(.*)
  static_files: notFound.htm
  upload: notFound.htm
  mime_type: text/html